print('good bye')
print('hello')
print('bye')
print('hi')
print('how r u')
print('bad')
print('confusing')
print('success')
print('gud mrng')
print('merge_conflict')
print('merge')
print('added- through-repo')
