print('good bye')
print('hello')
print('bye')
print('hi')
print('how r u')
print('bad')
print('confusing')
print('success')
print('28-2')
print('1-3')
print('added through repo')
print('dharani')
print('deleted through repo')
print('modified')